---
blank_issues_enabled: false
contact_links:
  - name: SecuritiesExamsMastery.ca Community Support
    url: https://github.com/MasteryEducation/SecuritiesExamsMastery.ca/discussions
    about: Please ask and answer questions here.
